sonar.projectKey=agenda_web
sonar.projectName=Agenda Web Contactos
sonar.projectVersion=1.0
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.token=sqa_db418af03327148216fce82867c045f2e9fb3110
sonar.sourceEncoding=UTF-8
